### ISSUE TITLE
Top video does not play on iOS

### ISSUE THREAD

**Issue by Sawaiz** [watergenics/website#3]
Tested on a IPhone X (maybe) and Iphone 8 (maybe as well).

Both using Brave browser and Safari (but I think all iOS browsers are safari under the hood. Can someone with a iPhone test this?

**Comment by cserb** [comment]
I can confirm. It's not playing on iPhone version 14.4.2

**Comment by Sawaiz** [comment]
No longer relevant, Video was removed.
